export const users = [
  { id: 1, name: 'Dulitha', age: 23 },
  { id: 2, name: 'Amila', age: 25 },
  { id: 3, name: 'Kasun', age: 35 },
  { id: 4, name: 'Nimali', age: 30 },
  { id: 5, name: 'Tharindu', age: 28 },
  { id: 6, name: 'Saman', age: 40 },
  { id: 7, name: 'Nadeesha', age: 22 },
  { id: 8, name: 'Chamara', age: 31 },
  { id: 9, name: 'Rashmi', age: 27 },
  { id: 10, name: 'Yasir', age: 29 },
  { id: 11, name: 'Meena', age: 33 },
  { id: 12, name: 'Ruwan', age: 26 },
  { id: 13, name: 'Lakshmi', age: 32 },
  { id: 14, name: 'Kamal', age: 34 },
  { id: 15, name: 'Sunil', age: 24 },
  { id: 16, name: 'Suhaila', age: 28 },
  { id: 17, name: 'Heshan', age: 27 },
  { id: 18, name: 'Anusha', age: 29 },
  { id: 19, name: 'Dilan', age: 21 },
  { id: 20, name: 'Priya', age: 26 },
  { id: 21, name: 'Harsha', age: 30 },
  { id: 22, name: 'Nuwan', age: 25 },
  { id: 23, name: 'Sangeetha', age: 22 },
  { id: 24, name: 'Aruna', age: 31 },
  { id: 25, name: 'Jayantha', age: 27 }
];
